---
# tasks file for initial-setting
- name: Load platform-specific variables
  include_vars: "{{ lookup('first_found', possible_files) }}"
  vars:
    possible_files:
      files:
        - '{{ ansible_distribution }}.yml'
        - '{{ ansible_os_family }}.yml'
        - 'default.yml'
      paths:
        - 'vars'

- name: Initial setting (Unix)
  import_tasks: Unix.yml
  when: ansible_os_family != 'Windows'

- name: Initial setting (Windows)
  import_tasks: Windows.yml
  when: ansible_os_family == 'Windows'