- name: Run the equivalent of "apt-get update" as a separate step
  ansible.builtin.apt:
    update_cache: yes

- name: Upgrade the OS (apt-get dist-upgrade)
  ansible.builtin.apt:
    upgrade: dist

- name: Update all packages to their latest version
  ansible.builtin.apt:
    name: "*"
    state: latest

- name: Ansible apt to install multiple packages - LAMP
  register: apt_installed
  apt:
    name: "{{ debian_packages }}"
    state: present
    update_cache: yes

- name: Remove dependencies that are no longer required
  ansible.builtin.apt:
    autoremove: yes

- name: Run the equivalent of "apt autoclean" as a separate step
  ansible.builtin.apt:
    autoclean: yes
